"use client";
import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FrequentQuestions = () => {
  return (
    <section className="flex flex-col md:items-center md:justify-center bg-primary-faq py-[80px] pt-[50px] md:mt-0 mt-[30px]">
      <div className="md:mb-[64px] mb-[40px]">
        <h4 className="text-text text-[24px] md:text-[40px] font-bold leading-[32.78px] md:leading-[54.64px] text-center px-[24px] w-[70%] md:w-full m-auto">
          Frequently Asked Questions
        </h4>
      </div>

      <div className="lg:max-w-[805px] md:max-w-[700px] w-full px-[24px]">
        <Accordion type="single" collapsible className="w-full items-start">
          <AccordionItem value="item-1">
            <AccordionTrigger className="text-left text-[16px] md:text-[24px] text-text-secondary leading-[22px] md:leading-[33px] font-[500]">
              What types of content can I create and transform with your tools?
            </AccordionTrigger>
            <AccordionContent className="text-[14px] md:text-[16px] text-text-secondary leading-[19.12px] md:leading-[21.86px] font-normal">
              You can convert text to videos, images to videos, and videos to
              thumbnails. Additionally, transcribe and summarize YouTube videos,
              podcasts, audio, and PDFs.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger className="text-left text-[16px] md:text-[24px] text-text-secondary leading-[22px] md:leading-[33px] font-[500]">
              How user-friendly are these tools for beginners?
            </AccordionTrigger>
            <AccordionContent className="text-[14px] md:text-[16px] text-text-secondary leading-[19.12px] md:leading-[21.86px] font-normal">
              Our tools are designed with user-friendliness in mind. Whether
              you&apos;re a beginner or an experienced content creator,
              you&apos;ll find our intuitive interfaces and straightforward
              processes easy to navigate and use.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger className="text-left text-[16px] md:text-[24px] text-text-secondary leading-[22px] md:leading-[33px] font-[500]">
              Can I customize the videos and thumbnails generated by these
              tools?
            </AccordionTrigger>
            <AccordionContent className="text-[14px] md:text-[16px] text-text-secondary leading-[19.12px] md:leading-[21.86px] font-normal">
              Yes, you can customize the videos and thumbnails. Our tools
              provide various options to add animations, visuals, and other
              custom elements to make your content unique and tailored to your
              needs.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-4">
            <AccordionTrigger className="text-left text-[16px] md:text-[24px] text-text-secondary leading-[22px] md:leading-[33px] font-[500]">
              How accurate are the transcriptions and summaries generated by
              your tools?
            </AccordionTrigger>
            <AccordionContent className="text-[14px] md:text-[16px] text-text-secondary leading-[19.12px] md:leading-[21.86px] font-normal">
              Our tools use advanced algorithms to ensure high accuracy in
              transcriptions and summaries. While we strive for precision, the
              quality of the output may vary depending on the clarity of the
              original content.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-5">
            <AccordionTrigger className="text-left text-[16px] md:text-[24px] text-text-secondary leading-[22px] md:leading-[33px] font-[500]">
              Do I need any special software or plugins to use these tools?
            </AccordionTrigger>
            <AccordionContent className="text-[14px] md:text-[16px] text-text-secondary leading-[19.12px] md:leading-[21.86px] font-normal">
              No special software or plugins are required. Our tools are
              web-based and can be accessed directly through your browser,
              making them convenient and accessible from any device with an
              internet connection.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-6">
            <AccordionTrigger className="text-left text-[16px] md:text-[24px] text-text-secondary leading-[22px] md:leading-[33px] font-[500]">
              Is my data secure when using your tools?
            </AccordionTrigger>
            <AccordionContent className="text-[14px] md:text-[16px] text-text-secondary leading-[19.12px] md:leading-[21.86px] font-normal">
              We prioritize the security and privacy of your data. All content
              processed through our tools is encrypted and stored securely. We
              do not share your data with third parties, ensuring the
              confidentiality of your information.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </section>
  );
};

export default FrequentQuestions;
